In [36]:
 from google.colab import drive
 drive.mount('/content/gdrive')
 %cd'gdrive/My Drive/Colab Notebooks/Thesis/Vietnam/GradientBoosting_Vietnam'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
[Errno 2] No such file or directory: 'gdrive/My Drive/Colab Notebooks/Thesis/Vietnam/GradientBoosting_Vietnam'
/content/gdrive/My Drive/Colab Notebooks/Thesis/Vietnam/GradientBoosting_Vietnam


In [37]:
import pandas as pd
data=pd.read_csv('baseline.csv')
test=data.copy()
test.head()

st_no   age     sex  ...  maxHCT_3to8  dmaxHCT_3to8 maxhemo_3to8
0     1  13.0    Male  ...          NaN           NaN          NaN
1  1000  12.0  Female  ...          NaN           NaN          NaN
2  1002  11.0    Male  ...         40.8           4.0     2.000000
3  1003  13.0    Male  ...         45.7           4.0    12.839506
4  1004  11.0    Male  ...         45.9           6.0    14.750000

[5 rows x 27 columns]

In [38]:
data.info()
data=data.replace('NA',None)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2301 entries, 0 to 2300
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   st_no           2301 non-null   object 
 1   age             2300 non-null   float64
 2   sex             2301 non-null   object 
 3   wt              2296 non-null   float64
 4   day_ill         2301 non-null   int64  
 5   his_tired       2298 non-null   object 
 6   his_vomit       2295 non-null   object 
 7   ttest           2289 non-null   object 
 8   temp            2299 non-null   float64
 9   pulse           2297 non-null   float64
 10  sys_bp          2298 non-null   float64
 11  mucosal_bleed   2283 non-null   object 
 12  abdominal_pain  2291 non-null   object 
 13  liver           2279 non-null   float64
 14  hct_bsl         2259 non-null   float64
 15  plt_bsl         2258 non-null   float64
 16  serotype2       2152 non-null   object 
 17  serology        2271 non-null   o

In [39]:

data.drop(['st_no', 'doi_shock'],axis='columns', inplace = True)

In [40]:
import numpy as np

In [41]:
conversion_parameters = ['sex' ,'his_tired','his_vomit','ttest','mucosal_bleed','abdominal_pain','serotype2','serology','to_PICU','shock','bleed_hos']
data[conversion_parameters] = np.where(pd.isnull(data[conversion_parameters]),data[conversion_parameters],data[conversion_parameters].astype(str))

In [42]:
from sklearn.preprocessing import LabelEncoder
en = LabelEncoder()
df = data.copy()

In [43]:
df[conversion_parameters] = df[conversion_parameters].astype("str").apply(en.fit_transform)
df = df.where(~data.isna(), data)
df


age  sex    wt  ...  maxHCT_3to8 dmaxHCT_3to8 maxhemo_3to8
0     13.0    1  31.0  ...          NaN          NaN          NaN
1     12.0    0  37.0  ...          NaN          NaN          NaN
2     11.0    1  27.0  ...         40.8          4.0     2.000000
3     13.0    1  20.0  ...         45.7          4.0    12.839506
4     11.0    1  27.0  ...         45.9          6.0    14.750000
...    ...  ...   ...  ...          ...          ...          ...
2296  13.0    0  39.0  ...         44.3          4.0    15.064935
2297  13.0    0  53.0  ...         42.0          5.0    10.526316
2298   9.0    0  27.5  ...         37.8          3.0     8.000000
2299  10.0    0  33.0  ...         43.0          5.0    16.216216
2300  15.0    0  49.0  ...         39.5          7.0    -2.469136

[2301 rows x 25 columns]

In [44]:
# check unique values for the conversion
for labels in conversion_parameters:
    print(f'{labels} : ',df[labels].unique())

sex :  [1 0]
his_tired :  [0 1 nan]
his_vomit :  [1 0 nan]
ttest :  [nan 1 2 0]
mucosal_bleed :  [0 1 nan]
abdominal_pain :  [1 0 nan]
serotype2 :  [1 3 0 5 2 nan 4]
serology :  [nan 0 3 2 1]
to_PICU :  [1 0]
shock :  [1 0]
bleed_hos :  [nan 1 0 3 2]


Filling up the missing value with KNN Imputer

In [45]:
import pandas as pd 
import numpy as np 
# importing the KNN from fancyimpute library 
from fancyimpute import KNN 

In [46]:
# calling the KNN class 
knn_imputer = KNN() 
# imputing the missing value with knn imputer 
arr_knn= knn_imputer.fit_transform(df) 
  

Imputing row 1/2301 with 13 missing, elapsed time: 1.036
Imputing row 101/2301 with 0 missing, elapsed time: 1.038
Imputing row 201/2301 with 0 missing, elapsed time: 1.039
Imputing row 301/2301 with 0 missing, elapsed time: 1.040
Imputing row 401/2301 with 0 missing, elapsed time: 1.042
Imputing row 501/2301 with 0 missing, elapsed time: 1.044
Imputing row 601/2301 with 0 missing, elapsed time: 1.045
Imputing row 701/2301 with 0 missing, elapsed time: 1.046
Imputing row 801/2301 with 2 missing, elapsed time: 1.047
Imputing row 901/2301 with 0 missing, elapsed time: 1.048
Imputing row 1001/2301 with 0 missing, elapsed time: 1.049
Imputing row 1101/2301 with 0 missing, elapsed time: 1.050
Imputing row 1201/2301 with 0 missing, elapsed time: 1.051
Imputing row 1301/2301 with 0 missing, elapsed time: 1.052
Imputing row 1401/2301 with 0 missing, elapsed time: 1.052
Imputing row 1501/2301 with 0 missing, elapsed time: 1.053
Imputing row 1601/2301 with 0 missing, elapsed time: 1.053
Imputing

In [47]:
df_knn = pd.DataFrame(data=arr_knn,columns=['age','sex','wt','day_ill','his_tired','his_vomit','ttest','temp','pulse','sys_bp','mucosal_bleed','abdominal_pain','liver','hct_bsl','plt_bsl','serotype2','serology','to_PICU','shock','bleed_hos','minPLT_3to8','dminPLT_3to8','maxHCT_3to8','dmaxHCT_3to8','maxhemo_3to8',])
df_knn.head()

age  sex    wt  ...  maxHCT_3to8  dmaxHCT_3to8  maxhemo_3to8
0  13.0  1.0  31.0  ...    49.697765      5.546672     26.030252
1  12.0  0.0  37.0  ...    44.886037      4.865776     16.097823
2  11.0  1.0  27.0  ...    40.800000      4.000000      2.000000
3  13.0  1.0  20.0  ...    45.700000      4.000000     12.839506
4  11.0  1.0  27.0  ...    45.900000      6.000000     14.750000

[5 rows x 25 columns]

In [48]:
df_knn = df_knn.astype(int)

In [49]:
# check unique values for the conversion
for labels in conversion_parameters:
    print(f'{labels} : ',df_knn[labels].unique())

sex :  [1 0]
his_tired :  [0 1]
his_vomit :  [1 0]
ttest :  [1 2 0]
mucosal_bleed :  [0 1]
abdominal_pain :  [1 0]
serotype2 :  [1 3 0 5 2 4]
serology :  [1 0 3 2]
to_PICU :  [1 0]
shock :  [1 0]
bleed_hos :  [1 0 3 2]


Gradient Boosting Classifier

age,sex,day_ill,his_tired,his_vomit,ttest,temp,pulse,sys_bp,mucosal_bleed,abdominal_pain,liver,hct_bsl,plt_bsl,to_picu,bleed_hos,shock

In [50]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier

In [51]:
feature_cols =['age','sex','day_ill','his_tired','his_vomit','ttest','temp','pulse','sys_bp','mucosal_bleed','abdominal_pain','liver','hct_bsl','plt_bsl','to_PICU','bleed_hos']
X=df_knn[feature_cols]
y=df_knn.shock
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

In [52]:
lr_list = [0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1]
depth=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,]

for learning_rate in lr_list:
  for max_depth_features in depth:
    gb_clf = GradientBoostingClassifier(n_estimators=100, learning_rate=learning_rate, max_features=max_depth_features, max_depth=max_depth_features, random_state=1,criterion='friedman_mse',verbose=1)
    gb_clf.fit(X_train, y_train)
    predictions = gb_clf.predict(X_test)

    print("Learning rate: ", learning_rate)
    print("Max_depth: ",max_depth_features)
    print("Accuracy score (training): {0:.3f}".format(gb_clf.score(X_train, y_train)))
    print("Accuracy score (validation): {0:.3f}".format(gb_clf.score(X_test, y_test)))

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))

    print("Classification Report")
    print(classification_report(y_test, predictions))

      Iter       Train Loss   Remaining Time 
         1           0.4952            0.20s
         2           0.4950            0.15s
         3           0.4949            0.13s
         4           0.4949            0.11s
         5           0.4949            0.11s
         6           0.4948            0.11s
         7           0.4948            0.10s
         8           0.4933            0.10s
         9           0.4933            0.10s
        10           0.4921            0.10s
        20           0.4138            0.07s
        30           0.3678            0.05s
        40           0.3625            0.04s
        50           0.3052            0.03s
        60           0.3035            0.03s
        70           0.3019            0.02s
        80           0.2989            0.02s
        90           0.2969            0.01s
       100           0.2764            0.00s
Learning rate:  0.05
Max_depth:  1
Accuracy score (training): 0.932
Accuracy score (validation): 0.

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


        50           0.1071            0.06s
        60           0.0982            0.05s
        70           0.0868            0.04s
        80           0.0768            0.02s
        90           0.0706            0.01s
       100           0.0621            0.00s
Learning rate:  0.05
Max_depth:  3
Accuracy score (training): 0.992
Accuracy score (validation): 0.981
Confusion Matrix:
[[645  12]
 [  1  33]]
Classification Report
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       657
           1       0.73      0.97      0.84        34

    accuracy                           0.98       691
   macro avg       0.87      0.98      0.91       691
weighted avg       0.99      0.98      0.98       691

      Iter       Train Loss   Remaining Time 
         1           0.4136            0.14s
         2           0.3870            0.15s
         3           0.3481            0.15s
         4           0.3240            0.15s
         5 

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


         4           0.3138            0.14s
         5           0.3128            0.14s
         6           0.2804            0.14s
         7           0.2591            0.14s
         8           0.2563            0.14s
         9           0.2348            0.14s
        10           0.2264            0.14s
        20           0.1446            0.10s
        30           0.1085            0.08s
        40           0.0899            0.07s
        50           0.0756            0.05s
        60           0.0671            0.04s
        70           0.0589            0.03s
        80           0.0511            0.02s
        90           0.0466            0.01s
       100           0.0421            0.00s
Learning rate:  0.075
Max_depth:  3
Accuracy score (training): 0.993
Accuracy score (validation): 0.978
Confusion Matrix:
[[644  13]
 [  2  32]]
Classification Report
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       657
    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


        70       14077.0074            0.03s
        80       14077.0074            0.02s
        90       14077.0074            0.01s
       100       14077.0074            0.00s
Learning rate:  1
Max_depth:  3
Accuracy score (training): 0.942
Accuracy score (validation): 0.955
Confusion Matrix:
[[656   1]
 [ 30   4]]
Classification Report
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       657
           1       0.80      0.12      0.21        34

    accuracy                           0.96       691
   macro avg       0.88      0.56      0.59       691
weighted avg       0.95      0.96      0.94       691

      Iter       Train Loss   Remaining Time 
         1           0.2739            0.17s
         2           0.1662            0.18s
         3           0.1333            0.18s
         4           0.6167            0.19s
         5          21.1505            0.18s
         6 25420775928709.5273            0.18s
         7 

In [53]:
feature_cols =['age','sex','hct_bsl','plt_bsl','serotype2','serology','to_PICU','minPLT_3to8','dminPLT_3to8','maxHCT_3to8','dmaxHCT_3to8','maxhemo_3to8']
X=df_knn[feature_cols]
y=df_knn.shock
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

In [54]:
lr_list = [0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1]
depth=[1,2,3,4,5,6,7,8,9,10,11,12]

for learning_rate in lr_list:
  for max_depth_features in depth:
    gb_clf = GradientBoostingClassifier(n_estimators=100, learning_rate=learning_rate, max_features=max_depth_features, max_depth=max_depth_features, random_state=1,criterion='friedman_mse',verbose=1)
    gb_clf.fit(X_train, y_train)
    predictions = gb_clf.predict(X_test)

    print("Learning rate: ", learning_rate)
    print("Max_depth: ",max_depth_features)
    print("Accuracy score (training): {0:.3f}".format(gb_clf.score(X_train, y_train)))
    print("Accuracy score (validation): {0:.3f}".format(gb_clf.score(X_test, y_test)))

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))

    print("Classification Report")
    print(classification_report(y_test, predictions))

      Iter       Train Loss   Remaining Time 
         1           0.4938            0.18s
         2           0.4155            0.17s
         3           0.4030            0.17s
         4           0.4025            0.16s
         5           0.3927            0.16s
         6           0.3846            0.15s
         7           0.3781            0.14s
         8           0.3723            0.14s
         9           0.3663            0.14s
        10           0.3659            0.14s
        20           0.3203            0.09s
        30           0.2662            0.07s
        40           0.2447            0.05s
        50           0.2139            0.04s
        60           0.1970            0.03s
        70           0.1748            0.02s
        80           0.1696            0.01s
        90           0.1647            0.01s
       100           0.1492            0.00s
Learning rate:  0.05
Max_depth:  1
Accuracy score (training): 0.972
Accuracy score (validation): 0.

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


        50 141414243898728891204990576631710193695749491925188608.0000            0.06s
        60 141414243898728891204990576631710193695749491925188608.0000            0.05s
        70 141414243898728891204990576631710193695749491925188608.0000            0.04s
        80 141414243898728891204990576631710193695749491925188608.0000            0.03s
        90 141414243898728891204990576631710193695749491925188608.0000            0.01s
       100 141414243898728891204990576631710193695749491925188608.0000            0.00s
Learning rate:  1
Max_depth:  3
Accuracy score (training): 0.055
Accuracy score (validation): 0.039
Confusion Matrix:
[[ 12 645]
 [ 19  15]]
Classification Report
              precision    recall  f1-score   support

           0       0.39      0.02      0.03       657
           1       0.02      0.44      0.04        34

    accuracy                           0.04       691
   macro avg       0.20      0.23      0.04       691
weighted avg       0.37      0.04    